package br.com.janes.vision.domain;

public enum FeatureType {

	TYPE_UNSPECIFIED, LANDMARK_DETECTION, FACE_DETECTION, LOGO_DETECTION, LABEL_DETECTION, TEXT_DETECTION, DOCUMENT_TEXT_DETECTION, SAFE_SEARCH_DETECTION, IMAGE_PROPERTIES, CROP_HINTS, WEB_DETECTION;
}
